version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    rules:
      - path: ".*_test\\.go$"
        linters:
          - errcheck
