version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet

issues:
  exclude-use-default: false
  exclude-rules:
    # Tests: keep signal high; production code should be strict.
    - path: ".*_test\\.go$"
      linters:
        - errcheck

linters-settings:
  errcheck:
    # Do not allow implicit ignoring; require explicit handling or `_ = ...`.
    check-type-assertions: true
    check-blank: true
